# Generated by Django 3.0.7 on 2020-06-23 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Address'),
        ),
    ]
