# Generated by Django 3.0.7 on 2020-06-25 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200623_1402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='address',
        ),
        migrations.AddField(
            model_name='store',
            name='address',
            field=models.ManyToManyField(to='core.Address'),
        ),
    ]
