# Generated by Django 3.0.7 on 2020-06-25 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200625_0717'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='address',
            new_name='addresses',
        ),
    ]
