# Generated by Django 3.0.7 on 2020-06-29 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='date_issued',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name=''),
        ),
    ]
